- name: Attaching AWAF Policy
  hosts: awaf_demo
  gather_facts: no
  connection: local
  collections:
  - f5networks.f5_modules

  tasks:

    - name: Import AWAF security policy
      bigip_asm_policy_import:
        provider: "{{ provider }}"
        name: ASP01
        source: /root/.ansible/Common_ASP01__2021-4-1_11-12-53__bigip01.example.local.xml

    - name: Create local traffic policy
      bigip_policy:
        provider: "{{ provider }}"
        name: l7-policy
        state: present
      when: inventory_hostname in groups['awaf_demo_master']

    - name: Add a rule to the new policy
      bigip_policy_rule:
        provider: "{{ provider }}"
        policy: l7-policy
        name: rule1
        conditions:
          - type: all_traffic
        actions:
          - type: enable
            asm_policy: ASP01
      when: inventory_hostname in groups['awaf_demo_master']

    - name: Attach the policy to the virtual server
      bigip_command:
        provider: "{{ provider }}"
        commands:
          - modify ltm virtual vs_webserver profiles add { websecurity }
          - modify ltm virtual vs_webserver policies add { l7-policy }
      when: inventory_hostname in groups['awaf_demo_master']

    - name: Add a logging profile to virtual server
      bigip_virtual_server:
        provider: "{{ provider }}"
        state: present
        partition: Common
        name: "vs_webserver"
        security_log_profiles: "Log all requests"
      when: inventory_hostname in groups['awaf_demo_master']

    # - name: making sure it's blocked mode
    #   bigip_command:
    #     provider: "{{ provider }}"
    #     commands:
    #       - modify asm policy ASP01 blocking-mode enabled
    #
    - name: Apply the policy
      bigip_asm_policy_manage:
        provider: "{{ provider }}"
        name: ASP01
        state: present
        apply: yes

  post_tasks:

    - name: Save the running BIG-IP configuration to disk
      bigip_config:
        provider: "{{ provider }}"
        save: True
      register: result
