---
bigip_hostname: bigip01.example.local

bigip_lic: "ZMONA-QRNRK-FVNBD-VGOXM-GBGXONP"

nf_selfIP:
  - selfIP: 192.168.10.24
    netmask: 255.255.255.0
    vlan_name: external
    port_lockdown: none
  - selfIP: 192.168.20.24
    netmask: 255.255.255.0
    vlan_name: internal
    port_lockdown: default
  - selfIP: 192.168.40.24
    netmask: 255.255.255.0
    vlan_name: ha
    port_lockdown: default

ha_selfip: '192.168.40.24'

peer_mgmt: 192.168.50.26
peer_hostname: bigip02.example.local
